// Registry of interactive drill components.
// Every entry is subject-tagged so a future multi-teacher system can filter
// drills by the active teacher's subject without schema changes.

import { lazy } from "react";

export const DRILL_MODES = [
  {
    id: "number-line",
    subject: "math",
    label: "שכנים על ציר המספרים",
    emoji: "🔢",
    grades: ["א'", "ב'", "ג'", "ד'", "ה'", "ו'", "ז'", "ח'"],
    topics: ["ציר המספרים", "מספרים עוקבים", "סדר עולה", "קפיצות", "מספרים שליליים"],
    component: lazy(() => import("@/pages/drills/NumberLine")),
  },
  {
    id: "times-table-sprint",
    subject: "math",
    label: "לוח הכפל מהיר",
    emoji: "⚡",
    grades: ["ב'", "ג'", "ד'", "ה'", "ו'"],
    topics: ["לוח הכפל", "כפל בעל-פה", "שינון"],
    component: lazy(() => import("@/pages/drills/TimesTableSprint")),
  },
  {
    id: "clock-reading",
    subject: "math",
    label: "קריאת שעון",
    emoji: "🕒",
    grades: ["א'", "ב'", "ג'", "ד'"],
    topics: ["שעון", "זמן", "שעות ודקות"],
    component: lazy(() => import("@/pages/drills/ClockReading")),
  },
  {
    id: "vertical-add",
    subject: "math",
    label: "חיבור מאונך",
    emoji: "➕",
    grades: ["א'", "ב'", "ג'", "ד'", "ה'", "ו'"],
    topics: ["חיבור מאונך", "נשא"],
    component: lazy(() => import("@/pages/drills/VerticalAddSub")),
  },
  {
    id: "vertical-sub",
    subject: "math",
    label: "חיסור מאונך",
    emoji: "➖",
    grades: ["א'", "ב'", "ג'", "ד'", "ה'", "ו'"],
    topics: ["חיסור מאונך", "שאילה"],
    component: lazy(() => import("@/pages/drills/VerticalAddSub")),
  },
  {
    id: "vertical-multiplication",
    subject: "math",
    label: "כפל מאונך",
    emoji: "📐",
    grades: ["ג'", "ד'", "ה'", "ו'"],
    topics: ["לוח הכפל", "כפל מאונך", "כפל דו-ספרתי בחד-ספרתי", "כפל דו-ספרתי בדו-ספרתי"],
    component: lazy(() => import("@/pages/drills/VerticalPractice")),
  },
  {
    id: "division-remainder",
    subject: "math",
    label: "חילוק עם שארית",
    emoji: "🧩",
    grades: ["ב'", "ג'", "ד'"],
    topics: ["חילוק עם שארית", "חילוק פשוט"],
    component: lazy(() => import("@/pages/drills/DivisionRemainder")),
  },
  {
    id: "long-division",
    subject: "math",
    label: "חילוק ארוך",
    emoji: "➗",
    grades: ["ד'", "ה'", "ו'"],
    topics: ["חילוק עם שארית", "חילוק ארוך"],
    component: lazy(() => import("@/pages/drills/LongDivision")),
  },
  {
    id: "pizza-fractions",
    subject: "math",
    label: "שברים עם פיצה",
    emoji: "🍕",
    grades: ["ד'", "ה'", "ו'"],
    topics: ["שברים", "שברים פשוטים", "חיבור וחיסור שברים", "שברים שקולים", "השוואת שברים"],
    component: lazy(() => import("@/pages/drills/PizzaFractions")),
  },
  {
    id: "integer-ops",
    subject: "math",
    label: "שלמים שליליים",
    emoji: "➕➖",
    grades: ["ז'", "ח'"],
    topics: ["חיבור וחיסור שלמים", "מספרים שליליים", "ערך מוחלט"],
    component: lazy(() => import("@/pages/drills/IntegerOps")),
  },
  {
    id: "alphabet-practice",
    subject: "english",
    label: "אותיות ABC",
    emoji: "🔤",
    grades: ["א'", "ב'", "ג'"],
    topics: ["אותיות", "אלף-בית", "ABC"],
    component: lazy(() => import("@/pages/drills/AlphabetPractice")),
  },
  {
    id: "letter-flashcards",
    subject: "english",
    label: "כרטיסיות אותיות",
    emoji: "🃏",
    grades: ["א'", "ב'", "ג'"],
    topics: ["אותיות", "הגייה", "כרטיסיות"],
    component: lazy(() => import("@/pages/drills/LetterFlashcards")),
  },
  {
    id: "letter-fill-in",
    subject: "english",
    label: "השלמת אותיות",
    emoji: "✏️",
    grades: ["א'", "ב'", "ג'"],
    topics: ["אותיות", "השלמה", "איות"],
    component: lazy(() => import("@/pages/drills/LetterFillIn")),
  },
  {
    id: "word-match",
    subject: "english",
    label: "התאמת מילים",
    emoji: "🃏",
    grades: ["א'", "ב'", "ג'", "ד'", "ה'", "ו'", "ז'", "ח'"],
    topics: ["אוצר מילים", "תרגום", "התאמה"],
    component: lazy(() => import("@/pages/drills/WordMatch")),
  },
  {
    id: "spelling-sprint",
    subject: "english",
    label: "איות מהיר",
    emoji: "✍️",
    grades: ["א'", "ב'", "ג'", "ד'", "ה'", "ו'", "ז'", "ח'"],
    topics: ["איות", "כתיבה", "אוצר מילים"],
    component: lazy(() => import("@/pages/drills/SpellingSprint")),
  },
  {
    id: "sentence-fill",
    subject: "english",
    label: "השלמת משפטים",
    emoji: "📝",
    grades: ["א'", "ב'", "ג'", "ד'", "ה'", "ו'", "ז'", "ח'"],
    topics: ["משפטים", "הבנה", "אוצר מילים"],
    component: lazy(() => import("@/pages/drills/SentenceFill")),
  },
  {
    id: "grammar-fix",
    subject: "english",
    label: "דקדוק אנגלי",
    emoji: "🔧",
    grades: ["א'", "ב'", "ג'", "ד'", "ה'", "ו'", "ז'", "ח'"],
    topics: ["דקדוק", "זמנים", "פועלים", "מילות יחס"],
    component: lazy(() => import("@/pages/drills/GrammarFix")),
  },
  {
    id: "reading-comp",
    subject: "english",
    label: "הבנת הנקרא",
    emoji: "📖",
    grades: ["א'", "ב'", "ג'", "ד'", "ה'", "ו'", "ז'", "ח'"],
    topics: ["הבנת הנקרא", "קריאה", "אוצר מילים"],
    component: lazy(() => import("@/pages/drills/ReadingComp")),
  },
  {
    id: "sentence-reorder",
    subject: "english",
    label: "סדר מילים",
    emoji: "🔀",
    grades: ["א'", "ב'", "ג'", "ד'", "ה'", "ו'", "ז'", "ח'"],
    topics: ["סדר מילים", "מבנה משפט", "תחביר"],
    component: lazy(() => import("@/pages/drills/SentenceReorder")),
  },
  {
    id: "irregular-verbs",
    subject: "english",
    label: "פעלים יוצאי דופן",
    emoji: "🔄",
    grades: ["ב'", "ג'", "ד'", "ה'", "ו'", "ז'", "ח'"],
    topics: ["פעלים", "עבר", "פעלים חריגים"],
    component: lazy(() => import("@/pages/drills/IrregularVerbs")),
  },
  {
    id: "confusing-words",
    subject: "english",
    label: "מילים מבלבלות",
    emoji: "🤔",
    grades: ["א'", "ב'", "ג'", "ד'", "ה'", "ו'", "ז'", "ח'"],
    topics: ["מילים מבלבלות", "אוצר מילים", "דקדוק"],
    component: lazy(() => import("@/pages/drills/ConfusingWords")),
  },
  {
    id: "mimad-session",
    subject: "mimad",
    label: "סימולציה + תרגול",
    emoji: "🏁",
    grades: ["א'", "ב'", "ג'", "ד'", "ה'", "ו'", "ז'", "ח'", "ט'", "י'", "י״א", "י״ב"],
    topics: ["סימולציית מבחן", "תרגול עם הסברים", "כמותי", "עברית", "אנגלית"],
    component: lazy(() => import("@/pages/drills/MimadSession")),
  },
];

export const drillsForGrade = (grade, subject = "math") =>
  DRILL_MODES.filter(d => d.subject === subject && d.grades.includes(grade));

export const drillById = (id) => DRILL_MODES.find(d => d.id === id);
